### PR TITLE
Fixing URLs and branches

### PR DESCRIPTION
**Pull request by Julius278**
### What does this PR do?
fix for new URL (web3j to hyperledger) including one branch fix (master to main)

### Where should the reviewer start?
doesn't matter, changes are indenpendent for each class / file

### Why is it needed?
branch name and repository owner changed

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've added tests (if applicable).
- [x] I've added a changelog entry if necessary.

### CODE REVIEW

**Comment by Julius278** [comment]
comparable adjustments as @NickSneo did in #2028

**Comment by Julius278** [comment]
Test pipeline: https://github.com/Julius278/web3j/actions/runs/10162422088

no new tests needed, and I would guess no changelog addition needed

**Review by NickSneo — COMMENTED** [review]
Well, these are all auto generated code, so it is not really required to change code in every file, we can anyways generate those and replace with new one. But thanks for your efforts.

**Comment by Julius278** [comment]
Hey Nick, yes most of them are auto generated and could be removed from the merge request. But some changes like the README or Generator.java are changes that will make a difference.

Also I would suggest creating a class which holds the code comment String to not have duplicated code in case they are all identical. If you want, I could check that.

**Comment by NickSneo** [comment]
> Hey Nick, yes most of them are auto generated and could be removed from the merge request. But some changes like the README or Generator.java are changes that will make a difference.
> 
> Also I would suggest creating a class which holds the code comment String to not have duplicated code in case they are all identical. If you want, I could check that.

Sure, you can look into it and create a PR we are happy to review

**Review by NickSneo — APPROVED** [review]
LGTM

**Pull request merged**
