### PR TITLE
Hotfix/4.9.8/update bouncycastle

### PR DESCRIPTION
**Pull request by TalhaAli00**
### What does this PR do?
Updates BouncyCastle to latest secure version. This is also a fix for an Android version

### Where should the reviewer start?
utils build.gradle 

### Why is it needed?
There are security vulnerabilities with the Java 1.5 version of BouncyCastle

## Checklist

- [x] I've read the contribution guidelines.
- [ ] I've added tests (if applicable).
- [ ] I've added a changelog entry if necessary.

### CODE REVIEW

**Comment by TalhaAli00** [comment]
CC: @NickSneo

**Comment by NickSneo** [comment]
> CC: @NickSneo

Hey @TalhaAli00 ,

Thanks for the PR, LGTM. We are planning to release 4.9.9-android with this commit.

**Review by NickSneo — APPROVED** [review]

**Comment by TalhaAli00** [comment]
@NickSneo do you have a timeline on when this will be released? I'd like to get this patch into our own release later this week

**Comment by NickSneo** [comment]
> @NickSneo do you have a timeline on when this will be released? I'd like to get this patch into our own release later this week

Hey @TalhaAli00 , I am on priority on this only. We have pushed a new branch 4.8.9-android with your changes and few more fixes to work with JAVA 8. But since we have recently migrated our repo under Hyperledger, we are facing issue with  PGP keys in releasing - https://github.com/hyperledger/web3j/actions/runs/8696487897/job/23849858116

We are actively working on this and trying to fix our release process, kindly give us some time - a day more. 
Thanks

**Comment by NickSneo** [comment]
@TalhaAli00 
Update: Seems like this issue is blocking us to use GPG2.1 with current Gradle version - https://github.com/gradle/gradle/issues/888

Since we cant update the gradle which requires JAVA version update too, we are thinking to create a private repo in our previous web3j org and follow old release process

**Comment by NickSneo** [comment]
@TalhaAli00 

Update: Release 4.8.9-android has been released successfully - https://github.com/hyperledger/web3j/actions/runs/8711603446

Kindly check and let us know if it works fine for you with updated bouncyCastle

**Comment by NickSneo** [comment]
@TalhaAli00 

Update: Release 4.8.9-android has been released successfully - https://github.com/hyperledger/web3j/actions/runs/8711603446

Kindly check and let us know if it works fine for you with updated bouncyCastle

**Comment by TalhaAli00** [comment]
@NickSneo 
The fix was applied to the `4.9.8` JVM branch but your message said `4.8.9`. Was that a typo?

**Comment by TalhaAli00** [comment]
Is there a difference between the Android dependency and the JVM dependency? 

I did a comparison of `4.8.8` and `4.8.8-android`  and didn't see any difference. 

My thought was that if there are no differences between the JVM version and Android, then we could just use the `4.9.8` version since it's been updated more recently compared to the `4.8.8` and `4.8.8-android` versions

**Comment by NickSneo** [comment]
> Is there a difference between the Android dependency and the JVM dependency?
> 
> I did a comparison of `4.8.8` and `4.8.8-android` and didn't see any difference.
> 
> My thought was that if there are no differences between the JVM version and Android, then we could just use the `4.9.8` version since it's been updated more recently compared to the `4.8.8` and `4.8.8-android` versions

Hey @TalhaAli00 ,

I believe there used to differences between JVM version and Android version, but seems with last few android releases there were no differences, which we were not aware of (android releases stopped before we became maintainers thats why).

I have created a new release 4.9.8-hotfix with your commits and some necessary commits to fix releases - https://github.com/hyperledger/web3j/tree/release/4.9.8-hotfix

Release should complete soon - https://github.com/hyperledger/web3j/actions/runs/8734580633
Let us know if it works fine for you now?

P.S. also you can go ahead and close this PR as we have cherry-picked your commits for the 4.9.8-hotfix release

**Comment by TalhaAli00** [comment]
Thanks @NickSneo, I've verified that the dependency is available

**Comment by NickSneo** [comment]
@TalhaAli00 Thats great, thank you for contributing!

**Pull request closed without merging**
